Improve error messages when typeToCode throws an exception (#1450)
`typeToCode` can throw an expection, which reduces the error message to:

```
UnimplementedError: (InvalidTypeImpl) InvalidType
package:json_serializable/src/utils.dart 221:3              typeToCode
package:json_serializable/src/helper_core.dart 79:46        createInvalidGenerationError
...
```

This change improves the error message to something like this:

```
Could not generate `fromJson` code for `photos` because of type is unimplemented/unsupported/undefined.
package:picthrive_kiosk/ptclient/generated/consolidated_public.swagger.dart:2633:21
     ╷
2633 │   final List<Items> photos;
     │                     ^^^^^^
     ╵

```